# Fly.io configuration for gallery-service

app = "clintecker-gallery"
primary_region = "ord"  # Chicago

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512  # 512MB sufficient for pre-resized images

[env]
  PORT = "8080"
  AWS_REGION = "us-east-1"
  S3_MEDIA_BUCKET = "i.clintecker.com"
